### ISSUE TITLE
Add parser to get strings from getTranslatableStrings method

### ISSUE THREAD

**Issue by hissy** [mlocati/concrete5-translate-library#14]
It seems current parsers don't retrieve strings from the package's `getTranslatableStrings` method.
Let's add it.

https://documentation.concretecms.org/api/9.1.1/Concrete/Core/Package/Package.html#method_getTranslatableStrings

**Comment by mlocati** [comment]
The `getTranslatableStrings()` method is used to extract strings in a "live" Concrete installation, strings that can be translated in the "Translate Site Interface" dashboard page (see https://github.com/concretecms/concretecms/blob/9.1.3/concrete/src/Multilingual/Service/Extractor.php#L78).

The translation library is not meant to extract strings from installed packages (for example, it's also used by translate.concretecms.org to extract translatable strings from packages submitted to the Concrete marketplace).
