### ISSUE TITLE
Allow for custom dynamic parsers

### ISSUE THREAD

**Issue by gutig** [mlocati/concrete5-translate-library#17]
It would be really good if we could include our own custom dynamic parsers similar to what is here; 
https://github.com/concrete5-community/translation-library/blob/master/src/Parser/DynamicItem/Area.php

Would be good if we can define these classes in a config or perhaps add them in some other way for it to be picked up when you click "reload strings"

This would allow us to translate custom dashboard entities that we create that are used on the site

**Comment by mlocati** [comment]
See https://github.com/concrete5-community/translation-library/pull/20 and https://github.com/concretecms/concretecms/pull/12164
