### ISSUE TITLE
Site Name Parser?

### ISSUE THREAD

**Issue by hissy** [mlocati/concrete5-translate-library#4]
I'd like to translate site name from dashboard!

https://github.com/concrete5/concrete5/pull/3480

**Comment by mlocati** [comment]
It should already be possible (thanks to [this change](https://github.com/concrete5/concrete5/pull/3480/files#diff-5ee376d00226655e75e4b715e76f3e60R23)) using the dashboard page `/dashboard/system/multilingual/translate_interface` ...

Am I wrong?

**Comment by hissy** [comment]
Sorry, I can translate it with current develop brunch. Thanks.

**Comment by mlocati** [comment]
:ok_hand:
